---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: shippingservice
spec:
  connectTimeout: 15s
  failover:
    '*':
      targets:
        - peer: 'aks'
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: paymentservice
spec:
  connectTimeout: 15s
  failover:
    '*':
      targets:
        - peer: 'aks'
---